import * as std from 'std';
import * as os from 'os';
import * as core from 'core';
import * as db from 'db';
import * as uart from 'uart';
import * as socketcan from 'socketcan';
import * as gpio from 'gpio';
import * as kafka from 'kafka';
import * as mqtt from 'mqtt';
globalThis.std = std;
globalThis.os = os;
globalThis.core = core;
globalThis.db = db;
globalThis.uart = uart;
globalThis.socketcan = socketcan;
globalThis.gpio = gpio;
globalThis.kafka = kafka;
globalThis.mqtt = mqtt;
globalThis.gdata = {};